name: Node.js build
on:
  [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-v: [20.x, 22.x, 24.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-v }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-v }}

      - name: Install package.json dependencies
        run: npm install

      - name: Run Node.js test suite
        run: npm test

      - name: Run linting
        run: npm run lint
